#!/bin/bash

# Get directory of this script as DIR...
#
#  (https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself)
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Setup conda for this shell
#
# https://stackoverflow.com/questions/34534513/calling-conda-source-activate-from-bash-script
# 
eval "$("$HOME/anaconda3/bin/conda" shell.bash hook)"

conda activate "$DIR/env"
cd "$DIR/my-app"

echo "type ^C to exit the server..."
yarn start
echo "react dev server exited with code $?"
read -n 1 -r -s -p $'Press enter to close window...\n'
