#!/bin/bash

# Get directory of this script as DIR...
#
#  (https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself)
#
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Setup conda for this shell
#
# https://stackoverflow.com/questions/34534513/calling-conda-source-activate-from-bash-script
# 
eval "$("$HOME/anaconda3/bin/conda" shell.bash hook)"

conda activate "$DIR/env"

. "$DIR/env/.env"

sets=()
for VAR in $(egrep '^[A-Za-z0-9_]+=' env/.env | sed -e 's/=.*//')
do
   var=$(echo $VAR | tr '[:upper:]' '[:lower:]')
   value=$(eval echo \$$VAR)
   sets+=("envs.$var=$value")
done

echo firebase functions:config:set "${sets[@]}"
cd "$DIR/functions"
firebase login
firebase use $FIREBASE_PROJECT_ID
firebase functions:config:set "${sets[@]}"
npm install
firebase deploy --only functions
curl -H "Authorization: Bearer $(gcloud auth print-identity-token)" \
  $FIREBASE_FUNCTIONS_URL/hello
