#!/bin/bash

# https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

gnome-terminal --window-with-profile=dbrun -x "$DIR/db-start"
gnome-terminal --window-with-profile=dbrun -x "tail" -f "$DIR/db/log"
